#!/bin/bash

JAR=target/scala-2.11/get_money_back_2.11-0.1-SNAPSHOT.jar

if [ ! -e "$JAR" ]
then
  echo 'Compiling..' 1>&2
  sbt package 2>&1 1>/dev/null
fi

scala -cp "$JAR" se.ramn.getmoneyback.GetMoneyBack
